### ISSUE TITLE
Show status for specific dotfile Group

### ISSUE THREAD

**Issue by BioBox** [RaphGL/Tuckr#13]
Can we please be given the ability to check the status of a specific category using `tuckr status <name>`? Preferably with an optional quiet flag to return a status code.

PS: I found this on Reddit and I really love it thanks :smiley:

**Comment by RaphGL** [comment]
Hi, thanks for making the issue.
So, what would you expect from a `tuckr status <name>`?

> Preferably with an optional quiet flag to return a status code.

Also what do you mean by this? You want to suppress outputs when you only care about the status code when scripting?

**Comment by BioBox** [comment]
> So, what would you expect from a `tuckr status <name>`?

A colored `<name>: [Not]Symlinked` is what I had in mind.

You already wrote the answer to your last question. A quiet flag isn't something that I see myself using right now, but it wouldn't hurt to have.

**Comment by RaphGL** [comment]
I originally simply outputted conflict files below the table but that assumes that everyone knows what files go to which group.
Making the output suppression flag also seems reasonable and shouldn't take long to do either.

**Comment by RaphGL** [comment]
Status command now returns exit codes based on the current status of the dotfiles' groups and one can check status for specific files.

`tuckr status` - check status for all files. 
`tuckr status <groups...>` - check status for a list of files

When run, if one checks `$?` for the exit code, one should see:
- `0` Every group has been symlinked properly
- `1` Group hasn't been symlinked yet or there is a file in conflict in one of the specified groups
