### ISSUE TITLE
Feature: add push and pop

### ISSUE THREAD

**Issue by yonas** [RaphGL/Tuckr#18]
This would be nice as well.

**Comment by RaphGL** [comment]
I don't think it's "required" but it's created by default to make the user aware that it's an option. Try deleting the hooks directory, everything should still work correctly, but if you do try to run a hook specific command it'll tell u that there's no hooks.

**Comment by yonas** [comment]
You're right, the scripts are not required, but the subdirectory within `Hooks` is requried. For example, `.config/dotfiles/Hooks/tmux`. It would be nice not to have to create this sub-directory manually.

**Comment by RaphGL** [comment]
I've been meaning to implement a `tuckr push` and a `tuckr pop` command that would allow to easily add and remove dotfiles but since u can just use `mv` to do that it's been a low priority so far as I've been improving symlinkg tracking.
