### ISSUE TITLE
Request: Higher level documentation

### ISSUE THREAD

**Issue by rwv37** [RaphGL/Tuckr#20]
I've been using various *nix OSes (mostly FreeBSD) for, I don't know, 25 years or so, but it was only in the past year that I discovered Stow. It's a bit clunky in some ways, but once I got used to it, I've liked it very much. When I saw the other day that a "Super-powered replacement for GNU Stow" (i.e. Tuckr) had been ported to FreeBSD, I got excited.

I gather that I could probably use Tuckr to do whatever I'm currently doing with Stow, and more on top of that. But although the documentation includes low-level examples of _how_ to do various things, it doesn't really seem to have much in the way of higher-level stuff. For example, for the things that both Tuckr and Stow can do, _why_ is Tuckr's way of doing them better than Stow's way? And for the things that only Tuckr can do, _what_ are some real-life reasons for why might I _want_ to do those things?

I understand that this might not be a terribly high-priority request, but I do think it would be nice to include such stuff in the documentation. Thanks.

**Comment by RaphGL** [comment]
I might add something like this once I start moving over documentation into the wiki section.

> why is Tuckr's way of doing them better than Stow's way? 

Neither is inherently better than the other per se but stow has stalled in development (the maintainer has been busy and has yet to fix a well known bug that has been around for 2 years).
This project builds on top of the basic ideas of Stow. But it tries to be an opinionated dotfile manager to remove the need for a config file found in some other dotfile managers, but of course you could just use it to replace stow and still benefit from it.  

There's a few features that are stables of dotfile managers like hooks and secrets that I've added so far. But what makes tuckr a "super powered replacement" is that it validates all symlinks and lets you resolve conflicts with a single command. This is an important part of tuckr and it's probably what I've spend the most time in.

> what are some real-life reasons for why might I want to do those things?

Well, tuckr arose from my own needs. It's just features I needed or wanted from stow that it didn't have so I had to write scripts to cover those needs. 

Here's an example:
- Symlinks:
Well, stow doesn't really validate symlinks , so you can't  know what's deployed, what's in conflict or anything. the only way of knowing is manually checking and deploying symlink groups u want on the current platform. 
Tuckr lets u set what files should be included on what platform and u can easily know what's deployed and what's in conflict.
And you can handle it accordingly.

- Hooks: 
I have neovim and tmux and I want to set it up. First I'd need to symlink the dotfiles and then install packer and the npm and python libraries used by extensions, I just have a hook for that so once I try to symlink it `tuckr set nvim` it install all dependencies and deploys the symlinks

- Secrets:
If you have server tokens and github tokens on your pc but need to share it across devices but not compromise them u can just create a secret for it and let tuckr decrypt it onto your machine.  


Tuckr is still in development though and there's some features that will  be added and some bugs to be ironed out (mostly on windows). But so far I've completely replaced stow on my system but there's probably some use cases for more "advanced" stow users that are not covered by tuckr and can only be achieved by stow yet. One that comes to mind right now is that you cannot symlink files onto root just yet, so having a `/etc/pacman.conf` config deployed by tuckr is not yet possible, but it's a feature I intend to add in the future.

**Comment by rwv37** [comment]
Thanks!

I use Stow both for home directory things and for things akin to your ``/etc/pacman.conf`` example. When you say that the latter is not yet possible, do you mean it's not yet possible to deploy to ``/etc`` or such _from Tuckr files that are stored in some subdirectory of root's home directory_ (or whatever)?

I'm asking because the way I currently do it using Stow is to have separate Stow trees for separate "top" directories (e.g. ``/home/bob/stowfiles/tmux/.config/tmux`` for my personal ``tmux`` config, to which Stow would symlink from ``/home/bob/.config/tmux/``, but also ``/usr/local/etc/stowfiles/doas/doas.conf`` for the machine's ``doas`` config, to which Stow would symlink from ``/usr/local/etc/doas.conf``). So I'm wondering, are you also saying that that sort of thing -- i.e. storing the stowfiles in some directory _other than_ the user's home directory -- is also not possible?

If that's also not possible, I guess I'll start with just trying Tuckr for home directory stuff, but keep Stow for the others for now. Then (assuming I wind up liking Tuckr after I've actually used it) eventually migrate to it for everything when that is supported.

I don't mean to push you, and I understand that I can't hold you to it, but I'm wondering if there's any guess for about when the ``/etc/pacman.conf`` sort of thing will be supported?

**Comment by RaphGL** [comment]
> do you mean it's not yet possible to deploy to /etc or such from Tuckr files that are stored in some subdirectory of root's home directory (or whatever)?

yeah, it's been a planned feature for a while now but I was making sure that the features I've implemented so far were reliable first. 
I haven't felt the need to backup global configurations yet but if I'm not wrong the way to achieve it in stow is to choose a target for a group, this is very involved, tuckr has no notion of targets it (for now) implicitly assume everything will be deployed onto $HOME. The only thing you're supposed to care about is whether a group is or is not deployed, that way you just let tuckr take care of the details. 

I've thought about making a root group that contains subgroups or just make all dotfiles targetting root to be a single group (but this is less optimal imo).  This way tuckr knows where to put everything and you never have to think about it. I don't know what's the best approach to take to make it as nice as how it is for dotfiles targetting $HOME.

> I don't mean to push you, and I understand that I can't hold you to it, but I'm wondering if there's any guess for about when the /etc/pacman.conf sort of thing will be supported?

The moment I find a good approach for it :)
The way the code is setup I only have to change where the symlink is targeted, the challenge is just finding a nice way of doing it. This can be done in a day. So if you try tuckr and have an idea of an idiom for it that makes sense, please let me know.

**Comment by rwv37** [comment]
> if I'm not wrong the way to achieve it in stow is to choose a target for a group, this is very involved

Not sure I'm understanding here, but the way Stow does it (or, at least, the way I do it with Stow) seems pretty simple: By default, the target is the parent directory of the directory you're using ``stow`` from. There's nothing particularly special about ``$HOME``. If you put a stowfiles directory in ``$HOME``, the stuff in there will be installed into ``$HOME``, but if you put one somewhere else, it will be installed into that other place.

I guess it might be nice to have a way to unify everything so it can all be installed/checked/whatever _from_ a single place, but at least in my view that's not nearly as important as having a way to install things _to more_ than a single place. Perhaps there could be an option to use the stow-esque "target is parent" thing, and (when this option is enabled) Tuckr could do validation and conflict checking and whatnot in a local sense? So, for example, all your things that you store in ``/usr/local/etc/tuckrfiles``, which are all to be installed in ``usr/local/etc`` (and subdirectories), are checked for conflicts against _each other_, but _not_ against the things in (e.g.) ``/home/blah/tuckrfiles`` which are to be installed in ``/home/blah`` (and subdirectories).

**Comment by RaphGL** [comment]
> Not sure I'm understanding here, but the way Stow does it (or, at least, the way I do it with Stow) seems pretty simple: By default, the target is the parent directory of the directory you're using stow from. There's nothing particularly special about $HOME. If you put a stowfiles directory in $HOME, the stuff in there will be installed into $HOME, but if you put one somewhere else, it will be installed into that other place.

Yeah you're right, stow just symlinks onto the parent directory. What I meant is that if you have a `dotfiles/pacman` and u want to put it on the correct place u would have to put `/etc` as a target and then u'd have to do this for every group that requires such a thing. I'd rather the user state upfront where everything should go and then have it all handled for them with `tuckr add \*` or any of the other symlink related operations.

> I guess it might be nice to have a way to unify everything so it can all be installed/checked/whatever from a single place

Yeah, the file structure is used to validate symlinks. Also having a centralized dotfiles repo makes it easier to manage. But that also means that tuckr is more of a dotfile manager than a symlink manager (which stow actually is but everyone ended up adopting it as a dotfile managing method instead).

> but at least in my view that's not nearly as important as having a way to install things to more than a single place

Do you deploy the same dotfile to multiple places at once? what's your use case for that I'm curious

> Perhaps there could be an option to use the stow-esque "target is parent" thing, and (when this option is enabled) Tuckr could do validation and conflict checking and whatnot in a local sense? So, for example, all your things that you store in /usr/local/etc/tuckrfiles, which are all to be installed in usr/local/etc (and subdirectories), are checked for conflicts against each other, but not against the things in (e.g.) /home/blah/tuckrfiles which are to be installed in /home/blah (and subdirectories).

This could be achieved using the way tuckr already works. You could have a directory structure like this (note: the root thing is not implemented yet):
```
├── root
│   └── tuckrfiles
│       └── usr
│           └── local
│               └── etc
└── tuckrfiles
```
This would treat the files in them as completely different and deploy them accordingly (first to `/usr/local/etc` and second to `$HOME`). Now if you want to just symlink from `/usr/local/etc/tuckrfiles` to `/usr/local/etc`, just symlinking it manually would be better, as this falls more under "managing symlinks" then managing dotfiles.

Even if you did that with stow you would still need to remember that that you symlinked things there, for me to automate managing that I would need to bruteforce my way through and hunt the entire file system for any symlinks pointing to a dotfile owned by tuckr and this would overcomplicate the codebase and make validation way slower.

**Comment by rwv37** [comment]
>>but at least in my view that's not nearly as important as having a way to install things to more than a single place

>Do you deploy the same dotfile to multiple places at once? what's your use case for that I'm curious

No, sorry, I think I might have been unclear: I did not mean "install _one particular thing_ to more than a single place"; I meant "install one particular thing to one place, and _some other_ particular thing to _some other_ place.

For example, I'd want (say) ``tmux.conf`` somewhere within my home directory tree, but (say) ``php.ini`` somewhere within the machine's ``/usr/local/etc`` directory tree.

>Even if you did that with stow you would still need to remember that that you symlinked things there, for me to automate managing that I would need to bruteforce my way through and hunt the entire file system for any symlinks pointing to a dotfile owned by tuckr and this would overcomplicate the codebase and make validation way slower.

That's the sort of thing that led me to suggest having an option to consider validation and whatnot as a local thing - i.e. the things I store in ``/home/bob/tuckrfiles``, which are installed into various places in the ``/home/bob`` tree, can be validated _as a complete unit_, without caring about the things I store in ``/usr/local/etc/tuckrfiles`` (to be installed in various places within the ``/usr/local/etc`` tree). And vice-versa - the things in ``/usr/local/etc/tuckrfiles`` can be validated as a complete unit without caring about the things in ``/home/bob/tuckrfiles``.

**Comment by RaphGL** [comment]
> For example, I'd want (say) tmux.conf somewhere within my home directory tree, but (say) php.ini somewhere within the machine's /usr/local/etc directory tree.

You could do that like so
```
├── root
│   └── phpthing
│       └── usr
│           └── local
│               └── etc
 |                   └── php.ini
└── tmux
```
When you run `tuckr add tmux phpthing` it would add those to the paths you specified.

> That's the sort of thing that led me to suggest having an option to consider validation and whatnot as a local thing - i.e. the things I store in /home/bob/tuckrfiles, which are installed into various places in the /home/bob tree, can be validated as a complete unit, without caring about the things I store in /usr/local/etc/tuckrfiles (to be installed in various places within the /usr/local/etc tree). And vice-versa - the things in /usr/local/etc/tuckrfiles can be validated as a complete unit without caring about the things in /home/bob/tuckrfiles.

If I understood you right, you're saying you'd want the root tuckrfiles and the home tuckrfiles to be treated as separate groups (ie units). So if you wanted to do that in the current way tuckr functions /would function you'd just name them differently like `tuckrfiles` and `global_tuckrfiles` or something.

But since tuckr is still being worked on and root targeting is not implemented yet, I think if you could argue that root configs are most often than not not related to the configurations of the user (which I guess is valid thinking back on what I've written here), making it so that groups targeting root are treated as a separate unit, so one would find tuckr treating them as `tuckrfiles` and `root/tuckrfiles` groups. And well since u need root privilege to symlink them it would be more explicit why those groups are failing to symlink or whatever. 

What u think?

**Comment by rwv37** [comment]
I feel like I'm not really understanding. I'm confused by things like "root targeting is not implemented yet" being alongside things like "you could do that like so". This sort of thing was confusing to me earlier in the thread, too. Could you please explain what you mean by "root targeting"? Thanks.

**Comment by RaphGL** [comment]
> I'm confused by things like "root targeting is not implemented yet"

I meant that there's no way yet to put dotfiles into the tuckr repo and have it be symlinked into a root path such as `/etc/pacman.conf` or `/usr/share`, etc. I was showing an hypothetical way of doing that ie "root targeting" by using a special `root` directory in tuckr.

So if you had `root/fonts` those fonts would symlink starting from `/` so you could install fonts by running `tuckr add root/fonts` or something like that.

**Comment by RaphGL** [comment]
Hey, I've written a small wiki on how to use the tool
It's still WIP so if there's any changes you would like to see, let me know
https://github.com/RaphGL/Tuckr/wiki

**Comment by RaphGL** [comment]
Closing issue as no response was given and the wiki is already up. If you have anything else to say about the documentation  reopen the issue and I'll try to improve it
