### ISSUE TITLE
Extend special folders to include `.local`

### ISSUE THREAD

**Issue by jrgirvan** [RaphGL/Tuckr#25]
I have some scripts in ~/.local/scripts that I manage with stow, but .local is used my many other applications

Tuckr does not link them.

Would be nice to extend the "special" folders to include `.local`
 
or perhaps, and this is probably a large change in the logic

drill down the folder structure until there is no conflicting folder and symlink that instead of the files/folders directly inside `Configs/config` 

https://github.com/RaphGL/Tuckr/blob/113a2579c8d086cc227d72be5aeca719a7382a21/src/utils.rs#L131-L134

**Comment by RaphGL** [comment]
Shallow symlinking has been implemented. No work arounds are necessary for this anymore.
For more information check https://github.com/RaphGL/Tuckr/issues/21#issuecomment-2212051295
