### ISSUE TITLE
`std::os::windows::fs::symlink_file` called on directory

### ISSUE THREAD

**Issue by Jasha10** [RaphGL/Tuckr#30]
On windows, you need to call a different function for symlinking files vs directories.
- [`std::os::windows::fs::symlink_dir`](https://doc.rust-lang.org/stable/std/os/windows/fs/fn.symlink_dir.html)	Creates a new symlink to a directory on the filesystem.
- [`std::os::windows::fs::symlink_file`](https://doc.rust-lang.org/stable/std/os/windows/fs/fn.symlink_file.html)	Creates a new symlink to a non-directory file on the filesystem.

Currently Tuckr always calls `symlink_file`, even if it is a directory being symlinked.
https://github.com/RaphGL/Tuckr/blob/dda9c9ca7c97a258c66b2e0694f6008ab06d5705/src/symlinks.rs#L33-L36

This leads to problems on Windows with the wrong type of symlink being created when Tuckr tries to create a symlink to a directory.

**Comment by RaphGL** [comment]
I somehow missed that detail on the documentation. Thank you!
